#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set quickstart.main.disable_dhns=1
	commit quickstart
EOF

uci -q batch <<-EOF >/dev/null
	set argon.@global[0].primary='#5b7e99'
	set argon.@global[0].dark_primary='#337d8c'
	commit argon
EOF

GATEWAY=
DNS=
WAN_GATEWAY=
WAN_DNS=
DHCP_SERVER=
WAN_IPV4_INPUT=

[ -n "$GATEWAY" ] && uci set network.lan.gateway="$GATEWAY"
if [ -n "$DNS" ]; then
	for dns in $DNS; do
		uci add_list network.lan.dns="$dns"
	done
fi

[ -n "$WAN_GATEWAY" ] && uci set network.wan.gateway="$WAN_GATEWAY"
if [ -n "$WAN_DNS" ]; then
	for dns in $WAN_DNS; do
		uci add_list network.wan.dns="$dns"
	done
fi
uci commit network

uci -q batch <<-EOF >/dev/null
	del dhcp.lan.ra
	del dhcp.lan.ra_slaac
	del dhcp.lan.ra_flags
	del dhcp.lan.dhcpv6
EOF

if [ "$WAN_IPV4_INPUT" = "1" -o "$WAN_IPV4_INPUT" = "on" ]; then
	section="$(uci add firewall rule)"
	uci set "firewall.$section.name=Allow-IPv4-WAN-Input"
	uci set "firewall.$section.src=wan"
	uci set "firewall.$section.family=ipv4"
	uci set "firewall.$section.target=ACCEPT"
	uci commit firewall
fi

if [ -n "$DHCP_SERVER" ]; then
	uci -q delete dhcp.lan.ignore
else
	uci set dhcp.lan.ignore='1'
fi
uci commit dhcp

exit 0
