#!/bin/sh /etc/rc.common

START=15

. /usr/lib/shadowrt/handoff.sh

load_dual_instance() {
	local proto
	SHADOWRT_INSTANCE_ID="$(uci -q get shadowrt.@instance[0].id)"
	SHADOWRT_LAN_ADDRESS="$(uci -q get shadowrt.@instance[0].lan_address)"
	proto="$(uci -q get shadowrt.@instance[0].proto)"
	case "$proto" in
		dual|dual_static) ;;
		*) return 1 ;;
	esac
	[ -n "$SHADOWRT_LAN_ADDRESS" ] || return 1
	shadowrt_handoff_names "$SHADOWRT_INSTANCE_ID"
}

reconcile() {
	load_dual_instance || return 0
	shadowrt_handoff_links
}

boot() {
	reconcile
}

start() {
	reconcile || return 1
	/etc/init.d/dockerd running || return 0
	docker network inspect "$SHADOWRT_DOCKER_NETWORK" -f '{{.Name}}' >/dev/null 2>&1 && return 0
	docker network create -d bridge \
		-o com.docker.network.bridge.inhibit_ipv4=true \
		-o "com.docker.network.bridge.name=$SHADOWRT_DOCKER_BRIDGE" \
		"$SHADOWRT_DOCKER_NETWORK"
}
